/* MTI_DPI */

/*
 * Copyright 2002-2011 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32'
 */
#ifndef INCLUDED_SHA_DPI
#define INCLUDED_SHA_DPI

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


DPI_LINK_DECL DPI_DLLESPEC
const char*
dpi_get_next_arg_c();

DPI_LINK_DECL DPI_DLLESPEC
const char*
dpi_get_tool_name_c();

DPI_LINK_DECL DPI_DLLESPEC
const char*
dpi_get_tool_version_c();

DPI_LINK_DECL DPI_DLLESPEC
void*
dpi_regcomp(
    const char* regex);

DPI_LINK_DECL DPI_DLLESPEC
int
dpi_regexec(
    void* preg,
    const char* str);

DPI_LINK_DECL DPI_DLLESPEC
void
dpi_regfree(
    void* preg);

DPI_LINK_DECL DPI_DLLESPEC
void
sha256_hash(
    const char* message,
    int msg_len,
    char* hash);

DPI_LINK_DECL DPI_DLLESPEC
void
uvm_dump_re_cache();

DPI_LINK_DECL DPI_DLLESPEC
const char*
uvm_glob_to_re(
    const char* glob);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_hdl_check_path(
    const char* path);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_hdl_deposit(
    const char* path,
    const svLogicVecVal* value);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_hdl_force(
    const char* path,
    const svLogicVecVal* value);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_hdl_read(
    const char* path,
    svLogicVecVal* value);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_hdl_release(
    const char* path);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_hdl_release_and_read(
    const char* path,
    svLogicVecVal* value);

DPI_LINK_DECL DPI_DLLESPEC
int
uvm_re_match(
    const char* re,
    const char* str);

#endif 
